name: "CI Workflow"
on: [push]

jobs:
  test:
    name: "Run tests against your code (eg: unit tests, style check, complexity check, etc...)."
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "run linter"
        uses: acreally/pylint-action@master
