name: Test
on: [push]

jobs:
  lint:
    name: "Lint check"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "run linter"
        run: pylint -f parseable src
