name: "CI Workflow"
on: [push]

jobs:
  test:
    name: "Run tests against your code (eg: unit tests, style check, complexity check, etc...)."
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "lint check"
        uses: acreally/pylint-action@master
      - name: "unit test"
        uses: acreally/pytest-action@master
  build:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.7
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: acreally/actions_demo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
