name: "CI Workflow"
on: [push]

jobs:
  test:
    name: "Run tests against your code (eg: unit tests, style check, complexity check, etc...)."
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "lint check"
        uses: acreally/pylint-action@master
      - name: "Setup python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: "unit test"
        run: |
          set -x
          mkdir -p artifacts/pytest
          pytest --junitxml=artifacts/pytest/junit.xml --cov-report html:artifacts/pytest/ --cov-report xml:artifacts/pytest/coverage.xml --cov=src test
      - name: "upload artifacts"
        uses: actions/upload-artifact@master
        with:
          name: test-artifacts
          path: artifacts
  build:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: acreally/actions_demo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
